// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metricsdocs

import (
	"fmt"
	"slices"
	"strings"
)

// preamble is everything above the first table row. The heading starts at level
// two because the documentation site includes this file into a page that already
// provides the title.
const preamble = "<!-- Generated by cmd/metrics-docs-gen from the metric definitions in internal/metrics. DO NOT EDIT. -->\n" +
	"<!-- To regenerate, run: make generate-metrics-docs -->\n" +
	"\n" +
	"## Controller Metrics\n" +
	"\n" +
	"Metric families declared by the `agent-sandbox-controller` for its metrics endpoint. The Go\n" +
	"runtime, process, and `controller-runtime` metrics that every controller-runtime manager exposes\n" +
	"are not listed here.\n" +
	"\n" +
	"| Metric | Type | Help | Labels |\n" +
	"| --- | --- | --- | --- |\n"

const noLabels = "None"

// helpEscaper neutralizes the characters that would otherwise end the table
// cell, be read as inline HTML, or be read as Markdown inline syntax. Help is
// the only cell carrying free-form prose: metric and label names need no
// escaping because extraction rejects anything outside the Prometheus name
// grammar. The backslash is escaped too, so one already in the help string
// cannot pair up with a character escaped here.
var helpEscaper = strings.NewReplacer(
	"\r\n", " ",
	"\r", " ",
	"\n", " ",
	`\`, `\\`,
	"|", `\|`,
	"&", "&amp;",
	"<", "&lt;",
	"*", `\*`,
	"[", `\[`,
	"`", "\\`",
)

// render returns the Markdown reference for families, in the order given.
func render(families []family) string {
	var out strings.Builder
	out.WriteString(preamble)
	for _, f := range families {
		out.WriteString(row(f))
	}
	return out.String()
}

func row(f family) string {
	return fmt.Sprintf("| `%s` | %s | %s | %s |\n",
		f.Name, f.Type, helpEscaper.Replace(f.Help), labelCell(f))
}

func labelCell(f family) string {
	labels := slices.Concat(f.Labels, f.ConstLabels)
	if len(labels) == 0 {
		return noLabels
	}
	quoted := make([]string, 0, len(labels))
	for _, label := range labels {
		quoted = append(quoted, "`"+label+"`")
	}
	return strings.Join(quoted, ", ")
}
