// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metricsdocs

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderRows(t *testing.T) {
	tests := []struct {
		name    string
		metric  family
		wantRow string
	}{
		{
			// One family carrying both label kinds states the whole ordering
			// contract.
			name: "variable labels keep declaration order and precede const labels",
			metric: family{
				Name:        "agent_sandbox_creation_latency_ms",
				Type:        typeHistogram,
				Help:        "Latency from Sandbox creation to Pod Ready state.",
				Labels:      []string{"namespace", "launch_type", "sandbox_template"},
				ConstLabels: []string{"build_date", "git_version"},
			},
			wantRow: "| `agent_sandbox_creation_latency_ms` | Histogram | Latency from Sandbox creation to Pod Ready state. | `namespace`, `launch_type`, `sandbox_template`, `build_date`, `git_version` |",
		},
		{
			name:    "metric without labels",
			metric:  family{Name: "agent_sandbox_up", Type: typeGauge, Help: "Up."},
			wantRow: "| `agent_sandbox_up` | Gauge | Up. | None |",
		},
		{
			name: "help text is escaped for the table",
			metric: family{
				Name: "agent_sandbox_up",
				Type: typeGauge,
				Help: "Either up | down.\nSecond line.\r\nThird line.",
			},
			wantRow: `| ` + "`agent_sandbox_up`" + ` | Gauge | Either up \| down. Second line. Third line. | None |`,
		},
		{
			// Help is the one cell taking free-form prose, so Markdown inline
			// syntax in it must not reach the site as formatting.
			name: "help text is escaped for Markdown",
			metric: family{
				Name: "agent_sandbox_up",
				Type: typeGauge,
				Help: `Rate is req*sec*ms. See [docs](http://x) and ` + "`up`" + `. A\B, C&D, x<y. Uses launch_type.`,
			},
			wantRow: "| `agent_sandbox_up` | Gauge | Rate is req\\*sec\\*ms. See \\[docs](http://x) and \\`up\\`. A\\\\B, C&amp;D, x&lt;y. Uses launch_type. | None |",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			out := render([]family{tc.metric})
			require.Contains(t, out, tc.wantRow+"\n")
		})
	}
}

func TestRenderDocumentShape(t *testing.T) {
	out := render([]family{{Name: "agent_sandbox_up", Type: typeGauge, Help: "Up."}})

	require.True(t, strings.HasPrefix(out, "<!-- Generated by cmd/metrics-docs-gen"), "output must open with a generated-file notice")
	require.Contains(t, out, "## Controller Metrics\n")
	require.Contains(t, out, "| Metric | Type | Help | Labels |\n| --- | --- | --- | --- |\n")
	require.True(t, strings.HasSuffix(out, "|\n"), "output must end with a complete row and a trailing newline")

	// Trailing whitespace survives gofmt but not most editors, so it would churn
	// the checked-in reference.
	for line := range strings.SplitSeq(out, "\n") {
		require.Equal(t, strings.TrimRight(line, " \t"), line, "lines must not carry trailing whitespace")
	}
}
