// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/clientset/versioned"
	internalinterfaces "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/informers/externalversions/internalinterfaces"
	apiv1beta1 "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/listers/api/v1beta1"
	extensionsapiv1beta1 "sigs.k8s.io/agent-sandbox/extensions/api/v1beta1"
)

// SandboxClaimInformer provides access to a shared informer and lister for
// SandboxClaims. Prefer using the type-safe variant (see [TypedSandboxClaimInformer]).
type SandboxClaimInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1beta1.SandboxClaimLister
}

// TypedSandboxClaimInformer provides access to a shared informer and lister for
// SandboxClaims, including the type-safe TypedInformer variant.
// It is a superset of SandboxClaimInformer.
type TypedSandboxClaimInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() SandboxClaimIndexInformer
	Lister() apiv1beta1.SandboxClaimLister
}

// SandboxClaimIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type SandboxClaimIndexInformer cache.TypedSharedIndexInformer[*extensionsapiv1beta1.SandboxClaim]

// SandboxClaimHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for SandboxClaim.
type SandboxClaimHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*extensionsapiv1beta1.SandboxClaim]

// SandboxClaimDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for SandboxClaim.
type SandboxClaimDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*extensionsapiv1beta1.SandboxClaim]

// SandboxClaimFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for SandboxClaim.
type SandboxClaimFilteringHandler = cache.TypedFilteringResourceEventHandler[*extensionsapiv1beta1.SandboxClaim]

// SandboxClaimIndexers is a specialization of [cache.TypedIndexers] for SandboxClaim.
type SandboxClaimIndexers = cache.TypedIndexers[*extensionsapiv1beta1.SandboxClaim]

// DeletedSandboxClaim is a specialization of [cache.DeletedObject] for SandboxClaim.
type DeletedSandboxClaim = cache.DeletedObject[*extensionsapiv1beta1.SandboxClaim]

type sandboxClaimInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSandboxClaimInformer constructs a new informer for SandboxClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSandboxClaimInformer]).
func NewSandboxClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewSandboxClaimInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedSandboxClaimInformer constructs a new informer for SandboxClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSandboxClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers SandboxClaimIndexers) SandboxClaimIndexInformer {
	return NewTypedSandboxClaimInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredSandboxClaimInformer constructs a new informer for SandboxClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredSandboxClaimInformer]).
func NewFilteredSandboxClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedSandboxClaimInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredSandboxClaimInformer constructs a new informer for SandboxClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredSandboxClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers SandboxClaimIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) SandboxClaimIndexInformer {
	return NewTypedSandboxClaimInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewSandboxClaimInformerWithOptions constructs a new informer for SandboxClaim type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSandboxClaimInformerWithOptions]).
func NewSandboxClaimInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedSandboxClaimInformerWithOptions(client, namespace, options)
}

// NewTypedSandboxClaimInformerWithOptions constructs a new informer for SandboxClaim type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSandboxClaimInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) SandboxClaimIndexInformer {
	gvr := schema.GroupVersionResource{Group: "extensions.agents.x-k8s.io", Version: "v1beta1", Resource: "sandboxclaims"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*extensionsapiv1beta1.SandboxClaim](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExtensionsV1beta1().SandboxClaims(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExtensionsV1beta1().SandboxClaims(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExtensionsV1beta1().SandboxClaims(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExtensionsV1beta1().SandboxClaims(namespace).Watch(ctx, opts)
			},
		}, client),
		&extensionsapiv1beta1.SandboxClaim{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *sandboxClaimInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedSandboxClaimInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *sandboxClaimInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *sandboxClaimInformer) TypedInformer() SandboxClaimIndexInformer {
	return cache.NewTypedSharedIndexInformer[*extensionsapiv1beta1.SandboxClaim](f.factory.InformerFor(&extensionsapiv1beta1.SandboxClaim{}, f.defaultInformer))
}

func (f *sandboxClaimInformer) Lister() apiv1beta1.SandboxClaimLister {
	return apiv1beta1.NewSandboxClaimLister(f.Informer().GetIndexer())
}

// ToTypedSandboxClaimInformer converts an untyped informer into a TypedSandboxClaimInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SandboxClaim. If that is not the case, calling type-safe methods of the returned
// TypedSandboxClaimInformer leads to runtime panics. A safer alternative is to pass
// around a TypedSandboxClaimInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedSandboxClaimInformer(informer SandboxClaimInformer) TypedSandboxClaimInformer {
	if informer, ok := informer.(TypedSandboxClaimInformer); ok {
		return informer
	}
	return &sandboxClaimTypedInformerAdapter{informer}
}

type sandboxClaimTypedInformerAdapter struct {
	SandboxClaimInformer
}

func (a *sandboxClaimTypedInformerAdapter) TypedInformer() SandboxClaimIndexInformer {
	return cache.NewTypedSharedIndexInformer[*extensionsapiv1beta1.SandboxClaim](a.Informer())
}

// ToSandboxClaimIndexInformer converts an untyped informer into a SandboxClaimIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SandboxClaim. If that is not the case, calling type-safe methods of the returned
// SandboxClaimIndexInformer leads to runtime panics. A safer alternative is to pass
// around a SandboxClaimIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToSandboxClaimIndexInformer(informer cache.SharedIndexInformer) SandboxClaimIndexInformer {
	if informer, ok := informer.(SandboxClaimIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*extensionsapiv1beta1.SandboxClaim](informer)
}
